Parameters:
  VpcId:
    Type: String
Resources:
  RookoutControllerFargateServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RookoutStack/RookoutControllerFargateService/Service/SecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId:
        Ref: VpcId
  RookoutControllerFargateServiceLBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Automatically created Security Group for ELB RookoutStackRookoutControllerFargateService
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow from anyone on port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      VpcId:
        Ref: VpcId
Outputs:
  RookoutControllerFargateServiceSecurityGroup:
    Value: !GetAtt RookoutControllerFargateServiceSecurityGroup.GroupId
  RookoutControllerFargateServiceLBSecurityGroup:
    Value: !GetAtt RookoutControllerFargateServiceLBSecurityGroup.GroupId