Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where resources will be deployed.
  PublicSubnetA:
    Type: AWS::EC2::Subnet::Id
  PublicSubnetB:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnets:
    Description: Select list of private subnets for ECS tasks. They should be in same
      VPC and has routes between PublicSubnets.
    Type: AWS::EC2::Subnet::Id
  HostedZone:
    Type: AWS::Route53::HostedZone::Id
  Domain:
    Type: String
  RookoutToken:
    Type: String
  DataStore:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
    Type: String
  Demo:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
    Type: String
  ControllerCPU:
    Default: 2048
    Type: String
  ControllerMemory:
    Default: 4096
    Type: String
  DataStoreCPU:
    Default: 2048
    Type: String
  DataStoreMemory:
    Default: 4096
    Type: String
Conditions:
  ShouldCreateDataStore:
    Fn::Equals:
    - true
    - Ref: DataStore
  ShouldCreateDemo:
    Fn::Equals:
    - true
    - Ref: Demo
Resources:
  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/28119bb8b857f05aa59887dc0ea3c95d.template
  Certificates:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/daa25d6a8a14a06bd650c84d195ec9dd.template
      Parameters:
        HostedZone:
          Ref: HostedZone
        Domain:
          Ref: Domain
  ControllerSG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/b439fc3e0b9993837bb891c66df7fbc4.template
      Parameters:
        VpcId:
          Ref: VpcId
  ControllerALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/44afb23b06f76a850e07931f26b678aa.template
      Parameters:
        PublicSubnetA:
          Ref: PublicSubnetA
        PublicSubnetB:
          Ref: PublicSubnetB
        RookoutControllerFargateServiceSecurityGroup:
          Fn::GetAtt:
          - ControllerSG
          - Outputs.RookoutControllerFargateServiceSecurityGroup
        RookoutControllerFargateServiceLBSecurityGroup:
          Fn::GetAtt:
          - ControllerSG
          - Outputs.RookoutControllerFargateServiceLBSecurityGroup
  ControllerIAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/acbdce7c03c7ae88f4cf23f6ca90acf1.template
  ControllerFargate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/5bfe5ceb692ce5ed3cbbd22cf27cbe58.template
      Parameters:
        VpcId:
          Ref: VpcId
        RookoutToken:
          Ref: RookoutToken
        PrivateSubnets:
          Ref: PrivateSubnets
        ControllerCPU:
          Ref: ControllerCPU
        ControllerMemory:
          Ref: ControllerMemory
        RookoutCluster:
          Fn::GetAtt:
          - ECS
          - Outputs.RookoutCluster
        RookoutCertificate:
          Fn::GetAtt:
          - Certificates
          - Outputs.RookoutCertificate
        RookoutControllerFargateServiceSecurityGroup:
          Fn::GetAtt:
          - ControllerSG
          - Outputs.RookoutControllerFargateServiceSecurityGroup
        RookoutControllerFargateServiceTaskDefTaskRole:
          Fn::GetAtt:
          - ControllerIAM
          - Outputs.RookoutControllerFargateServiceTaskDefTaskRole
        RookoutControllerFargateServiceTaskDefExecutionRole:
          Fn::GetAtt:
          - ControllerIAM
          - Outputs.RookoutControllerFargateServiceTaskDefExecutionRole
        RookoutControllerFargateServiceLBArn:
          Fn::GetAtt:
          - ControllerALB
          - Outputs.RookoutControllerFargateServiceLBArn
  ControllerRoute53:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/4290840e9c7c91c0718375f4d2635d5d.template
      Parameters:
        HostedZone:
          Ref: HostedZone
        Domain:
          Ref: Domain
        RookoutControllerFargateServiceLBDNSName:
          Fn::GetAtt:
          - ControllerALB
          - Outputs.RookoutControllerFargateServiceLBDNSName
        RookoutControllerFargateServiceLBCanonicalHostedZoneID:
          Fn::GetAtt:
          - ControllerALB
          - Outputs.RookoutControllerFargateServiceLBCanonicalHostedZoneID
  DataStoreSG:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDataStore
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/d5cb973d26e583f83c4443bcbd77dfe2.template
      Parameters:
        VpcId:
          Ref: VpcId
  DataStoreALB:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDataStore
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/93129ae66bc76061df51be34da12a343.template
      Parameters:
        PublicSubnetA:
          Ref: PublicSubnetA
        PublicSubnetB:
          Ref: PublicSubnetB
        RookoutDataStoreFargateServiceSecurityGroup:
          Fn::GetAtt:
          - DataStoreSG
          - Outputs.RookoutDataStoreFargateServiceSecurityGroup
        RookoutDataStoreFargateServiceLBSecurityGroup:
          Fn::GetAtt:
          - DataStoreSG
          - Outputs.RookoutDataStoreFargateServiceLBSecurityGroup
  DataStoreIAM:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDataStore
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/6dfcf6fcfe0e605df4a29429935f363e.template
  DataStoreFargate:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDataStore
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/ca406b5104bc45eecf79a747500ed877.template
      Parameters:
        VpcId:
          Ref: VpcId
        RookoutToken:
          Ref: RookoutToken
        PrivateSubnets:
          Ref: PrivateSubnets
        DataStoreCPU:
          Ref: ControllerCPU
        DataStoreMemory:
          Ref: ControllerMemory
        RookoutCluster:
          Fn::GetAtt:
          - ECS
          - Outputs.RookoutCluster
        RookoutCertificate:
          Fn::GetAtt:
          - Certificates
          - Outputs.RookoutCertificate
        RookoutDataStoreFargateServiceSecurityGroup:
          Fn::GetAtt:
          - DataStoreSG
          - Outputs.RookoutDataStoreFargateServiceSecurityGroup
        RookoutDataStoreFargateServiceTaskDefTaskRole:
          Fn::GetAtt:
          - DataStoreIAM
          - Outputs.RookoutDataStoreFargateServiceTaskDefTaskRole
        RookoutDataStoreFargateServiceTaskDefExecutionRole:
          Fn::GetAtt:
          - DataStoreIAM
          - Outputs.RookoutDataStoreFargateServiceTaskDefExecutionRole
        RookoutDataStoreFargateServiceLBArn:
          Fn::GetAtt:
          - DataStoreALB
          - Outputs.RookoutDataStoreFargateServiceLBArn
  DataStoreRoute53:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDataStore
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/19144cd8f421e4ba91695025077488db.template
      Parameters:
        HostedZone:
          Ref: HostedZone
        Domain:
          Ref: Domain
        RookoutDataStoreFargateServiceLBDNSName:
          Fn::GetAtt:
          - DataStoreALB
          - Outputs.RookoutDataStoreFargateServiceLBDNSName
        RookoutDataStoreFargateServiceLBCanonicalHostedZoneID:
          Fn::GetAtt:
          - DataStoreALB
          - Outputs.RookoutDataStoreFargateServiceLBCanonicalHostedZoneID
  DemoSG:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDemo
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/653744b2dd56917a70fe5eabd77479cf.template
      Parameters:
        VpcId:
          Ref: VpcId
  DemoALB:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDemo
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/0db2d61c6c3ce8ec31cf44ff078ca5b3.template
      Parameters:
        PublicSubnetA:
          Ref: PublicSubnetA
        PublicSubnetB:
          Ref: PublicSubnetB
        RookoutDemoFargateServiceSecurityGroup:
          Fn::GetAtt:
          - DemoSG
          - Outputs.RookoutDemoFargateServiceSecurityGroup
        RookoutDemoFargateServiceLBSecurityGroup:
          Fn::GetAtt:
          - DemoSG
          - Outputs.RookoutDemoFargateServiceLBSecurityGroup
  DemoIAM:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDemo
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/5071c301b7a88f16ede732a4d09a5b30.template
  DemoFargate:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDemo
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/1cb15e6946578bd5d1c112ac6fddd788.template
      Parameters:
        Domain:
          Ref: Domain
        VpcId:
          Ref: VpcId
        RookoutToken:
          Ref: RookoutToken
        PrivateSubnets:
          Ref: PrivateSubnets
        RookoutCluster:
          Fn::GetAtt:
          - ECS
          - Outputs.RookoutCluster
        RookoutCertificate:
          Fn::GetAtt:
          - Certificates
          - Outputs.RookoutCertificate
        RookoutDemoFargateServiceSecurityGroup:
          Fn::GetAtt:
          - DemoSG
          - Outputs.RookoutDemoFargateServiceSecurityGroup
        RookoutDemoFargateServiceTaskDefTaskRole:
          Fn::GetAtt:
          - DemoIAM
          - Outputs.RookoutDemoFargateServiceTaskDefTaskRole
        RookoutDemoFargateServiceTaskDefExecutionRole:
          Fn::GetAtt:
          - DemoIAM
          - Outputs.RookoutDemoFargateServiceTaskDefExecutionRole
        RookoutDemoFargateServiceLBArn:
          Fn::GetAtt:
          - DemoALB
          - Outputs.RookoutDemoFargateServiceLBArn
  DemoRoute53:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDemo
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/beb8238d618094115e740065a96daf2a.template
      Parameters:
        HostedZone:
          Ref: HostedZone
        Domain:
          Ref: Domain
        RookoutDemoFargateServiceLBDNSName:
          Fn::GetAtt:
          - DemoALB
          - Outputs.RookoutDemoFargateServiceLBDNSName
        RookoutDemoFargateServiceLBCanonicalHostedZoneID:
          Fn::GetAtt:
          - DemoALB
          - Outputs.RookoutDemoFargateServiceLBCanonicalHostedZoneID
