Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where resources will be deployed.
  PublicSubnetA:
    Type: AWS::EC2::Subnet::Id
  PublicSubnetB:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnets:
    Description: Select list of private subnets for ECS tasks. They should be in same
      VPC and has routes between PublicSubnets.
    Type: AWS::EC2::Subnet::Id
  HostedZone:
    Type: AWS::Route53::HostedZone::Id
  Domain:
    Type: String
  RookoutToken:
    Type: String
  DataStore:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
    Type: String
Conditions:
  ShouldCreateDataStore:
    Fn::Equals:
    - true
    - Ref: DataStore
Resources:
  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/28119bb8b857f05aa59887dc0ea3c95d.template
  Certificates:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/daa25d6a8a14a06bd650c84d195ec9dd.template
      Parameters:
        HostedZone:
          Ref: HostedZone
        Domain:
          Ref: Domain
  ControllerSG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/b439fc3e0b9993837bb891c66df7fbc4.template
      Parameters:
        VpcId:
          Ref: VpcId
  ControllerALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/44afb23b06f76a850e07931f26b678aa.template
      Parameters:
        PublicSubnetA:
          Ref: PublicSubnetA
        PublicSubnetB:
          Ref: PublicSubnetB
        RookoutControllerFargateServiceSecurityGroup:
          Fn::GetAtt:
          - ControllerSG
          - Outputs.RookoutControllerFargateServiceSecurityGroup
        RookoutControllerFargateServiceLBSecurityGroup:
          Fn::GetAtt:
          - ControllerSG
          - Outputs.RookoutControllerFargateServiceLBSecurityGroup
  ControllerIAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/acbdce7c03c7ae88f4cf23f6ca90acf1.template
  ControllerFargate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/a79de38e5e936bce62ccc482240e313b.template
      Parameters:
        VpcId:
          Ref: VpcId
        RookoutToken:
          Ref: RookoutToken
        PrivateSubnets:
          Ref: PrivateSubnets
        RookoutCluster:
          Fn::GetAtt:
          - ECS
          - Outputs.RookoutCluster
        RookoutCertificate:
          Fn::GetAtt:
          - Certificates
          - Outputs.RookoutCertificate
        RookoutControllerFargateServiceSecurityGroup:
          Fn::GetAtt:
          - ControllerSG
          - Outputs.RookoutControllerFargateServiceSecurityGroup
        RookoutControllerFargateServiceTaskDefTaskRole:
          Fn::GetAtt:
          - ControllerIAM
          - Outputs.RookoutControllerFargateServiceTaskDefTaskRole
        RookoutControllerFargateServiceTaskDefExecutionRole:
          Fn::GetAtt:
          - ControllerIAM
          - Outputs.RookoutControllerFargateServiceTaskDefExecutionRole
        RookoutControllerFargateServiceLBArn:
          Fn::GetAtt:
          - ControllerALB
          - Outputs.RookoutControllerFargateServiceLBArn
  DataStoreSG:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDataStore
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/d5cb973d26e583f83c4443bcbd77dfe2.template
      Parameters:
        VpcId:
          Ref: VpcId
  DataStoreALB:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDataStore
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/93129ae66bc76061df51be34da12a343.template
      Parameters:
        PublicSubnetA:
          Ref: PublicSubnetA
        PublicSubnetB:
          Ref: PublicSubnetB
        RookoutDataStoreFargateServiceSecurityGroup:
          Fn::GetAtt:
          - DataStoreSG
          - Outputs.RookoutDataStoreFargateServiceSecurityGroup
        RookoutDataStoreFargateServiceLBSecurityGroup:
          Fn::GetAtt:
          - DataStoreSG
          - Outputs.RookoutDataStoreFargateServiceLBSecurityGroup
  DataStoreIAM:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDataStore
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/6dfcf6fcfe0e605df4a29429935f363e.template
  DataStoreFargate:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDataStore
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/660c877493a5ce18be025a3fe7731a10.template
      Parameters:
        VpcId:
          Ref: VpcId
        RookoutToken:
          Ref: RookoutToken
        PrivateSubnets:
          Ref: PrivateSubnets
        RookoutCluster:
          Fn::GetAtt:
          - ECS
          - Outputs.RookoutCluster
        RookoutCertificate:
          Fn::GetAtt:
          - Certificates
          - Outputs.RookoutCertificate
        RookoutDataStoreFargateServiceSecurityGroup:
          Fn::GetAtt:
          - DataStoreSG
          - Outputs.RookoutDataStoreFargateServiceSecurityGroup
        RookoutDataStoreFargateServiceTaskDefTaskRole:
          Fn::GetAtt:
          - DataStoreIAM
          - Outputs.RookoutDataStoreFargateServiceTaskDefTaskRole
        RookoutDataStoreFargateServiceTaskDefExecutionRole:
          Fn::GetAtt:
          - DataStoreIAM
          - Outputs.RookoutDataStoreFargateServiceTaskDefExecutionRole
        RookoutDataStoreFargateServiceLBArn:
          Fn::GetAtt:
          - DataStoreALB
          - Outputs.RookoutDataStoreFargateServiceLBArn
  DataStoreRoute53:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateDataStore
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/19144cd8f421e4ba91695025077488db.template
      Parameters:
        HostedZone:
          Ref: HostedZone
        Domain:
          Ref: Domain
        RookoutDataStoreFargateServiceLBDNSName:
          Fn::GetAtt:
          - DataStoreALB
          - Outputs.RookoutDataStoreFargateServiceLBDNSName
        RookoutDataStoreFargateServiceLBCanonicalHostedZoneID:
          Fn::GetAtt:
          - DataStoreALB
          - Outputs.RookoutDataStoreFargateServiceLBCanonicalHostedZoneID
