Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where resources will be deployed.
  PublicSubnetA:
    Type: AWS::EC2::Subnet::Id
  PublicSubnetB:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnets:
    Description: Select list of private subnets for ECS tasks. They should be in same
      VPC and has routes between PublicSubnets.
    Type: AWS::EC2::Subnet::Id
  HostedZone:
    Type: AWS::Route53::HostedZone::Id
  Domain:
    Type: String
  RookoutToken:
    Type: String
Resources:
  ControllerSG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/b439fc3e0b9993837bb891c66df7fbc4.template
      Parameters:
        VpcId:
          Ref: VpcId
  ControllerALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/c4a7be53d77ebd9b840d9c7484549ade.template
      Parameters:
        PublicSubnetA:
          Ref: PublicSubnetA
        PublicSubnetB:
          Ref: PublicSubnetB
        RookoutControllerFargateServiceSecurityGroup:
          Fn::GetAtt:
          - ControllerSG
          - Outputs.RookoutControllerFargateServiceSecurityGroup
        RookoutControllerFargateServiceLBSecurityGroup:
          Fn::GetAtt:
          - ControllerSG
          - Outputs.RookoutControllerFargateServiceLBSecurityGroup
  ControllerIAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/acbdce7c03c7ae88f4cf23f6ca90acf1.template
  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/28119bb8b857f05aa59887dc0ea3c95d.template
  Certificates:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/75a127961c6a287ea6fb23a1ed8dedfb.template
      Parameters:
        HostedZone:
          Ref: HostedZone
        Domain:
          Ref: Domain
  ControllerFargate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/a79de38e5e936bce62ccc482240e313b.template
      Parameters:
        VpcId:
          Ref: VpcId
        RookoutToken:
          Ref: RookoutToken
        PrivateSubnets:
          Ref: PrivateSubnets
        RookoutCluster:
          Fn::GetAtt:
          - ECS
          - Outputs.RookoutCluster
        RookoutCertificate:
          Fn::GetAtt:
          - Certificates
          - Outputs.RookoutCertificate
        RookoutControllerFargateServiceSecurityGroup:
          Fn::GetAtt:
          - ControllerSG
          - Outputs.RookoutControllerFargateServiceSecurityGroup
        RookoutControllerFargateServiceTaskDefTaskRole:
          Fn::GetAtt:
          - ControllerIAM
          - Outputs.RookoutControllerFargateServiceTaskDefTaskRole
        RookoutControllerFargateServiceTaskDefExecutionRole:
          Fn::GetAtt:
          - ControllerIAM
          - Outputs.RookoutControllerFargateServiceTaskDefExecutionRole
        RookoutControllerFargateServiceLBArn:
          Fn::GetAtt:
          - ControllerALB
          - Outputs.RookoutControllerFargateServiceLBArn
  ControllerRoute53:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/alexey-cf/4290840e9c7c91c0718375f4d2635d5d.template
      Parameters:
        HostedZone:
          Ref: HostedZone
        Domain:
          Ref: Domain
        RookoutControllerFargateServiceLBDNSName:
          Fn::GetAtt:
          - ControllerALB
          - Outputs.RookoutControllerFargateServiceLBDNSName
        RookoutControllerFargateServiceLBCanonicalHostedZoneID:
          Fn::GetAtt:
          - ControllerALB
          - Outputs.RookoutControllerFargateServiceLBCanonicalHostedZoneID
