Parameters:

  VpcId:
    Type: AWS::EC2::VPC::Id
  RookoutCluster:
    Type: String
  RookoutToken:
    Type: String
  RookoutCertificate:
    Type: String
  PrivateSubnets:
    Type: String
  RookoutDemoFargateServiceTaskDefTaskRole:
    Type: String
  RookoutDemoFargateServiceTaskDefExecutionRole:
    Type: String
  RookoutDemoFargateServiceSecurityGroup:
    Type: String
  RookoutDemoFargateServiceLBArn:
    Type: String
  Domain:
    Type: String

Resources:
  RookoutDemoFargateServiceTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Environment:
            - Name: ROOKOUT_TOKEN
              Value:
                Ref: RookoutToken
            - Name: ROOKOUT_CONTROLLER_HOST
              Value:
                Fn::Join:
                  - ""
                  - - "wss://"
                    - controller.rookout.
                    - !Ref Domain
            - Name: ROOKOUT_CONTROLLER_PORT
              Value: 443
            - Name: ROOKOUT_REMOTE_ORIGIN
              Value: "https://github.com/Rookout/tutorial-python.git"
            - Name: ROOKOUT_COMMIT
              Value: "HEAD"
          Essential: true
          Image: rookout/tutorial-python:latest
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: RookoutDemoFargateServiceTaskDefDemoLogGroup
              awslogs-stream-prefix: RookoutDemoFargateService
              awslogs-region:
                Ref: AWS::Region
          Name: demo
          PortMappings:
            - ContainerPort: 5000
              Protocol: tcp
      Cpu: "512"
      ExecutionRoleArn: !Ref RookoutDemoFargateServiceTaskDefExecutionRole
      Family: RookoutStackRookoutDemoFargateServiceTaskDef
      Memory: "2048"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !Ref RookoutDemoFargateServiceTaskDefTaskRole

  RookoutDemoFargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: RookoutCluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DesiredCount: 1
      EnableECSManagedTags: false
      HealthCheckGracePeriodSeconds: 60
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: demo
          ContainerPort: 5000
          TargetGroupArn:
            Ref: RookoutDemoFargateServiceLBPublicListenerECSGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Ref: RookoutDemoFargateServiceSecurityGroup
          Subnets:
            - Ref: PrivateSubnets
      TaskDefinition:
        Ref: RookoutDemoFargateServiceTaskDef
    DependsOn:
      - RookoutDemoFargateServiceLBPublicListenerECSGroup
      - RookoutDemoFargateServiceLBPublicListener

  RookoutDemoFargateServiceLBPublicListenerECSGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: "/todos"
      Port: 5000
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: "false"
      TargetType: ip
      VpcId:
        Ref: VpcId

  RookoutDemoFargateServiceLBPublicListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: RookoutDemoFargateServiceLBPublicListenerECSGroup
          Type: forward
      LoadBalancerArn:
        Ref: RookoutDemoFargateServiceLBArn
      Certificates:
        - CertificateArn:
            Ref: RookoutCertificate
      Port: 443
      Protocol: HTTPS

  RookoutDemoFargateServiceTaskDefExecutionRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - RookoutDemoFargateServiceTaskDefDemoLogGroup
                - Arn
        Version: "2012-10-17"
      PolicyName: RookoutDemoFargateServiceTaskDefExecutionRoleDefaultPolicy
      Roles:
        - Ref: RookoutDemoFargateServiceTaskDefExecutionRole

  RookoutDemoFargateServiceTaskDefDemoLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain