Parameters:
  HostedZone:
    Type: AWS::Route53::HostedZone::Id
  Domain:
    Type: String
  RookoutDemoFargateServiceLBDNSName:
    Type: String
  RookoutDemoFargateServiceLBCanonicalHostedZoneID:
    Type: String
Resources:
  RookoutDemoFargateServiceDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        Fn::Join:
          - ""
          - - demo.rookout.
            - Ref: Domain
            - "."
      Type: A
      AliasTarget:
        DNSName:
          Fn::Join:
            - ""
            - - dualstack.
              - Ref: RookoutDemoFargateServiceLBDNSName
        HostedZoneId:
          Ref: RookoutDemoFargateServiceLBCanonicalHostedZoneID
      HostedZoneId:
        Ref: HostedZone