Parameters:
  HostedZone:
    Type: AWS::Route53::HostedZone::Id
  Domain:
    Type: String
  RookoutControllerFargateServiceLBDNSName:
    Type: String
  RookoutControllerFargateServiceLBCanonicalHostedZoneID:
    Type: String
Resources:
  RookoutControllerFargateServiceDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        Fn::Join:
          - ""
          - - controller.rookout.
            - Ref: Domain
            - "."
      Type: A
      AliasTarget:
        DNSName:
          Fn::Join:
            - ""
            - - dualstack.
              - Ref: RookoutControllerFargateServiceLBDNSName
        HostedZoneId:
          Ref: RookoutControllerFargateServiceLBCanonicalHostedZoneID
      HostedZoneId:
        Ref: HostedZone