Parameters:
  HostedZone:
    Type: String
  Domain:
    Type: String
  RookoutDataStoreFargateServiceLBDNSName:
    Type: String
  RookoutDataStoreFargateServiceLBCanonicalHostedZoneID:
    Type: String
Resources:
  RookoutDataStoreFargateServiceDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        Fn::Join:
          - ""
          - - datastore.rookout.
            - Ref: Domain
            - "."
      Type: A
      AliasTarget:
        DNSName:
          Fn::Join:
            - ""
            - - dualstack.
              - Ref: RookoutDataStoreFargateServiceLBDNSName
        HostedZoneId:
          Ref: RookoutDataStoreFargateServiceLBCanonicalHostedZoneID
      HostedZoneId:
        Ref: HostedZone