Parameters:
  RookoutControllerFargateServiceSecurityGroup:
    Type: String
  RookoutControllerFargateServiceLBSecurityGroup:
    Type: String
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String
Resources:
  RookoutControllerFargateServiceLBSecurityGrouptoRookoutStackRookoutControllerFargateServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref RookoutControllerFargateServiceLBSecurityGroup
      IpProtocol: tcp
      Description: Load balancer to target
      DestinationSecurityGroupId: !Ref RookoutControllerFargateServiceSecurityGroup
      FromPort: 7488
      ToPort: 7488
  RookoutControllerFargateServiceSecurityGroupfromRookoutStackRookoutControllerFargateServiceLBSecurityGroup:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: Load balancer to target
      FromPort: 7488
      GroupId: !Ref RookoutControllerFargateServiceSecurityGroup
      SourceSecurityGroupId: !Ref RookoutControllerFargateServiceLBSecurityGroup
      ToPort: 7488
  RookoutControllerFargateServiceLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: "false"
      Scheme: internet-facing
      SecurityGroups:
        - Ref: RookoutControllerFargateServiceLBSecurityGroup
      Subnets:
        - Ref: PublicSubnet1
        - Ref: PublicSubnet2
      Type: application
Outputs:
  RookoutControllerFargateServiceLBArn:
    Value: !Ref RookoutControllerFargateServiceLB
  RookoutControllerFargateServiceLBDNSName:
    Value: !GetAtt RookoutControllerFargateServiceLB.DNSName
  RookoutControllerFargateServiceLBCanonicalHostedZoneID:
    Value: !GetAtt RookoutControllerFargateServiceLB.CanonicalHostedZoneID